var fs = require('fs');

var content = [
'Add-Type -AssemblyName System.Windows.Forms',
'Add-Type -AssemblyName System.Drawing',
'function Make-Icon($c) {',
'  $b=New-Object System.Drawing.Bitmap(16,16)',
'  $g=[System.Drawing.Graphics]::FromImage($b)',
'  $g.SmoothingMode="AntiAlias"',
'  $g.Clear([System.Drawing.Color]::Transparent)',
'  $br=New-Object System.Drawing.SolidBrush([System.Drawing.Color]::$c)',
'  $g.FillEllipse($br,1,1,13,13)',
'  $g.Dispose(); $br.Dispose()',
'  return [System.Drawing.Icon]::FromHandle($b.GetHicon())',
'}',
'$iG=Make-Icon "LimeGreen"',
'$iR=Make-Icon "OrangeRed"',
'$iY=Make-Icon "Gold"',
'$t=New-Object System.Windows.Forms.NotifyIcon',
'$t.Icon=$iY',
'$t.Text="Server Checking..."',
'$t.Visible=$true',
'$m=New-Object System.Windows.Forms.ContextMenuStrip',
'$ms=$m.Items.Add("Status: Checking...")',
'$m.Items.Add("-") | Out-Null',
'$m1=$m.Items.Add("[Start]   Server Start")',
'$m2=$m.Items.Add("[Stop]    Server Stop")',
'$m3=$m.Items.Add("[Restart] Server Restart")',
'$m.Items.Add("-") | Out-Null',
'$m4=$m.Items.Add("[Log]  View Logs")',
'$m5=$m.Items.Add("[Open] Open Browser")',
'$m.Items.Add("-") | Out-Null',
'$m6=$m.Items.Add("[Exit] Exit")',
'$t.ContextMenuStrip=$m',
'$m1.Add_Click({ Start-Process "cmd" -ArgumentList "/c pm2 start daelimsystem" -WindowStyle Hidden })',
'$m2.Add_Click({ Start-Process "cmd" -ArgumentList "/c pm2 stop daelimsystem" -WindowStyle Hidden })',
'$m3.Add_Click({ Start-Process "cmd" -ArgumentList "/c pm2 restart daelimsystem" -WindowStyle Hidden })',
'$m4.Add_Click({ Start-Process "cmd" -ArgumentList "/k pm2 logs daelimsystem --lines 50" })',
'$m5.Add_Click({ Start-Process "http://localhost:3000" })',
'$t.Add_DoubleClick({ Start-Process "http://localhost:3000" })',
'$m6.Add_Click({ $tmr.Stop(); $t.Visible=$false; $t.Dispose(); [System.Windows.Forms.Application]::Exit() })',
'$tmr=New-Object System.Windows.Forms.Timer',
'$tmr.Interval=5000',
'$tmr.Add_Tick({',
'  try {',
'    $r=[System.Net.WebRequest]::Create("http://localhost:3000/api/auth/me")',
'    $r.Timeout=3000',
'    $rs=$r.GetResponse(); $rs.Close()',
'    $t.Icon=$iG; $t.Text="Server: Online"',
'    $ms.Text="Status: Online"',
'  } catch {',
'    $t.Icon=$iR; $t.Text="Server: OFFLINE !"',
'    $ms.Text="Status: OFFLINE"',
'    try { $t.ShowBalloonTip(3000,"Server Alert","Server is not responding.",[System.Windows.Forms.ToolTipIcon]::Warning) } catch {}',
'  }',
'})',
'$tmr.Start()',
'[System.Windows.Forms.Application]::Run()'
].join('\r\n');

fs.writeFileSync('D:/price-list-app/server-tray.ps1', content, 'ascii');
console.log('server-tray.ps1 created OK');
